export enum EActionType {
	PRIORITY_SEND_ORDER = "PRIORITY_SEND_ORDER",
	PRIORITY_FETCH_PRODUCTS = "PRIORITY_FETCH_PRODUCTS",
	PRIORITY_LOAD_EXCEL = "PRIORITY_LOAD_EXCEL",
	CASHCOW_FETCH_ORDER = "CASHCOW_FETCH_ORDER",
	CASHCOW_SEND_PRODUCTS = "CASHCOW_SEND_PRODUCTS",
	CASHCOW_LOAD_EXCEL = "CASHCOW_LOAD_EXCEL",
}

export enum EActionStatus {
	FAILED = "FAILED",
	SUCCESS = "SUCCESS",
}
