export enum ECashcowAddOrUpdateQtyType {
    Units = 0,
    Kg = 1,
    Grams = 2,
    Liter = 3,
    Meter = 4,
    Cm = 5,
}

export enum ECashcowOrderStatus {
    PhoneBankTransfer = 1,
    Lead = 2,
    Paid = 4,
    Error = 5,
    Delivered = 6,
    PendingReview = 7,
    Canceled = 8,
    Claimed = 9,
}

export enum ECashcowOrderPaymentType {
    Paypal = 1,
    Redirect = 2,
    Phone = 3,
    BankTransfer = 4,
    Pelepay = 5,
    PaypalExpress = 6,
    Netpay = 7,
    Tranzilla = 8,
    GPrimium = 9,
    CreditGuard = 10,
    EasyCard = 11,
    ZCredit = 12,
    PayCard = 13,
    Cardcom = 14,
    AuthorizeNet = 15,
    PeleCard = 16,
    Cellarix = 17,
    Verifone = 18,
    Stripe = 19,
    TwoCheckout = 20,
    PayMe = 21,
    CashCowCalExpress = 30,
    Credit2000 = 40,
    ICredit = 45,
    PayPlus = 50,
    Meshulam = 52,
    YaadSarig = 55,
    ZeroPayment = 799,
    VerifoneBrand2 = 57,
    MeshulamBit = 58,
    PayPlusEMV = 59,
    ZCreditEMV = 60,
    Api = 61
}